extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  elasticsearch/logs:
    endpoints: [http://elasticsearch:9200]
    tls:
      insecure_skip_verify: true
    index: otel_logs_index

  prometheus:
    endpoint: 0.0.0.0:9090
    namespace: otel

  otlphttp/jaeger:
    endpoint: http://jaeger:4318
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [elasticsearch/logs]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/jaeger]

  extensions: [health_check]