scrape_configs:
  - job_name: otel-collector
    scrape_interval: 10s
    static_configs:
      - targets: ['otelcol:9090']
  - job_name: nats-surveyor
    scrape_interval: 5s
    static_configs:
      - targets: ['nats-observe:7777']